@cleancodeprojectwebapi_HostAddress = https://localhost:7275

GET {{cleancodeprojectwebapi_HostAddress}}/api/restaurants
Accept: application/json

###

###

GET {{cleancodeprojectwebapi_HostAddress}}/api/restaurants/2
Accept: application/json

###

POST {{cleancodeprojectwebapi_HostAddress}}/api/restaurants
Content-Type: application/json
{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Fine Dining",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54321"
}