@cleancodeprojectwebapi_HostAddress = https://localhost:7275

GET {{cleancodeprojectwebapi_HostAddress}}/api/restaurants
Accept: application/json

###

###

GET {{cleancodeprojectwebapi_HostAddress}}/api/restaurants/2
Accept: application/json

###

POST {{cleancodeprojectwebapi_HostAddress}}/api/restaurants
Content-Type: application/json
{
      "Name": "Tasty Bites",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "IndianI",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}